# Generated by Django 5.0.6 on 2024-06-10 09:47

import portfolio_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0005_alter_aboutme_options_alter_contact_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutme',
            name='styling_image',
            field=models.ImageField(upload_to='assets/about_me/', validators=[portfolio_app.models.validate_image_extension]),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='background_image',
            field=models.ImageField(upload_to='assets/profile_image/'),
        ),
    ]
