# Generated by Django 5.0.6 on 2024-06-10 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0007_alter_aboutme_styling_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='blog_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='github_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='live_demo_url',
            field=models.URLField(blank=True),
        ),
    ]
